name: working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: Run the workflow in dry-run mode
        default: false
      target:
        type: environment
        required: true
        description: Which environment workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: default values

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo tag
        run: |
          echo "Selected tag is: ${{ inputs.tag }}"

  deploy:
    # only run when dry_run is false
    if: ${{ !inputs.dry_run }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo environment
        run: |
          echo "Target environment is: ${{ inputs.target }}"
