name : using the cache
on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Wether to execute the cahche
        type: boolean
        default: true

jobs:
  builds:
    runs-on : ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name:  install dependencies
        run : npm ci
      - name : testing
        run : npm run test
      - name : building
        run : npm run build








